[Icon Theme]
Name=Sweet
Comment=Purple folders for sweet theme.
Inherits=candy,breeze-dark,hicolor
FollowsColorScheme=true

# Directory list
Directories=Actions,Emblems,Places,Status


[Actions]
Context=Actions
Size=22
MinSize=8
MaxSize=512
Type=Scalable

[Emblems]
Context=Emblems
Size=22
Type=Scalable
MinSize=8
MaxSize=512

[Places]
Context=Places
Size=96
MinSize=8
MaxSize=512
Type=Scalable

[Status]
Context=Status
Size=22
Type=Scalable
MinSize=8
MaxSize=512
